services:
  mysql:
    container_name: app-mysql
    image: mysql:8.0.32
    restart: on-failure
    build:
      context: .
    volumes:
#      - /root/docker/compose/mysql/data:/var/lib/mysql
      - ./deploy/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=888888
      - MYSQL_DATABASE=cook-master
    ports:
      - "3306:3306"
    command:
      --authentication_policy=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci

#    networks:
#      - my-server

  app:
    # 容器名称
    container_name: app
    # 构建目录
    build:
      context: .
      dockerfile: prod.Dockerfile
    # 重启规则
    restart: on-failure # 设置自动重启，这一步必须设置，主要是存在mysql还没有启动完成就启动了node服务
    # 暴露端口
    expose:
      - 3000
    ports:
      - 3000:3000
    # 构建依赖
    depends_on:
      - mysql
    env_file:
      - .env
    # 环境变量
    environment:
      - RUN_TIME_ENV=local
    # 网桥
#    networks:
#      - my-server

#  networks:
#    my-server: